In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense

In [3]:
X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])

y = np.array([4,5,6,7])

X = X.reshape((X.shape[0], X.shape[1], 1))
print(X)

[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Input

In [5]:
model = Sequential()

In [6]:
model.add(Input(shape=(3,1)))

In [7]:
model.add(GRU(50, activation='tanh'))

In [8]:
model.add(Dense(1))

In [9]:
model.compile(optimizer='adam', loss='mse')

In [10]:
model.fit(X, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 624ms/step - loss: 39.2778
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 38.2655
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 37.2711
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 36.2937
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 35.3321
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 34.3853
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 33.4527
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32.5338
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 31.6284
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 30.7361
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 29.8568
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 28.9901
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 28.1358
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 27.2936
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 26.4633
Epo